# Generated by Django 5.0.3 on 2024-09-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
