# Generated by Django 5.0.3 on 2024-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id_dough', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('cost', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dough',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id_filling', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, null=True)),
                ('cost', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'filling',
                'db_table_comment': 'эрўшэър\nъюысрёр, уЁшс√ (ъ ёюцрыхэш■, эх уры■Ўшэюухээ√х) ш яЁюўр\xa0 тъєёэр\xa0, р шэюуфр ш эх тъєёэр\xa0 °Єєър',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(blank=True, null=True)),
                ('id_pizza', models.IntegerField(blank=True, null=True)),
                ('cost', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PizzaConstr',
            fields=[
                ('id_pizza', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_name', models.CharField(blank=True, null=True)),
                ('id_users', models.IntegerField(blank=True, null=True)),
                ('id_dough', models.IntegerField(blank=True, null=True)),
                ('id_sauce', models.IntegerField(blank=True, null=True)),
                ('id_fillings', models.IntegerField(blank=True, null=True)),
                ('cost', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pizza_constr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id_reviews', models.AutoField(primary_key=True, serialize=False)),
                ('id_order', models.IntegerField(blank=True, null=True)),
                ('id_user', models.IntegerField(blank=True, null=True)),
                ('review', models.CharField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'db_table_comment': 'юЄч√т√',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id_sauce', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, null=True)),
                ('cost', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sauce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_users', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('login', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
