# Generated by Django 5.0.3 on 2024-04-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillingPizzaConstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'filling_pizza_constr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersPizzaConstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'orders_pizza_constr',
                'managed': False,
            },
        ),
        migrations.AlterModelTableComment(
            name='filling',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='reviews',
            table_comment=None,
        ),
    ]
