# Generated by Django 5.0.3 on 2024-04-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fillingpizzaconstr_orderspizzaconstr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaConstrFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_constr_id_filling', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'pizza_constr_filling',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FillingPizzaConstr',
        ),
    ]
