# Generated by Django 5.0.3 on 2024-09-06 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pizzaconstrfilling_delete_fillingpizzaconstr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
